stages:
  - build
  - deploy

maven-build:
  image: maven:3.6.3-openjdk-11
  stage: build
  script:
    - mvn clean install jib:build -Djib.to.image=docker.io/"$DOCKER_HUB_USER"/$DOCKER_HUB_REPO:"$CI_COMMIT_REF_NAME" -Djib.to.auth.username="$DOCKER_HUB_USER" -Djib.to.auth.password="$DOCKER_HUB_TOKEN" -Djib.to.tags=${CI_COMMIT_SHA}
    - mvn jib:build -Djib.to.auth.username=${CI_REGISTRY_USER} -Djib.to.auth.password=${CI_REGISTRY_PASSWORD} -Djib.to.image=${CI_REGISTRY_IMAGE}:"$CI_COMMIT_REF_NAME" -Djib.to.tags=${CI_COMMIT_SHA}

  only:
    refs:
      - main
      - develop

deploy-HH-WP-WEBADMIN-dev:
  stage: deploy
  image: dtzar/helm-kubectl:2.13.0
  script:
    - kubectl config set-cluster local --server="${HH_WP_WEBADMIN_ENDPOINT}"
    - kubectl config set clusters.local.certificate-authority-data "${HH_WP_WEBADMIN_CERTIFICATE_AUTHORITY}"
    - kubectl config set-credentials ${HH_WP_WEBADMIN_DEV_USER} --token="${HH_WP_WEBADMIN_DEV_USER_TOKEN}"
    - kubectl config set-context "${HH_WP_WEBADMIN_DEV_NAMESPACE}" --cluster=local --user=${HH_WP_WEBADMIN_DEV_USER} --namespace="${HH_WP_WEBADMIN_DEV_NAMESPACE}"
    - kubectl config use-context "${HH_WP_WEBADMIN_DEV_NAMESPACE}"
    - kubectl version

    - sed -i "s/latest/$CI_COMMIT_SHA/g" k8-deploy/dev/pdcm-admin-api-dev-deployment.yaml

    - kubectl apply -f k8-deploy/dev/pdcm-admin-api-dev-deployment.yaml --record
    - kubectl rollout status -f k8-deploy/dev/pdcm-admin-api-dev-deployment.yaml

    - kubectl apply -f k8-deploy/dev/pdcm-admin-api-dev-service.yaml --record
    - kubectl get pods,service,deploy,replicaset,ing -n "${HH_WP_WEBADMIN_DEV_NAMESPACE}"
  only:
    refs:
      - develop

deploy-HH-WP-WEBADMIN-master:
  stage: deploy
  image: dtzar/helm-kubectl:2.13.0
  script:
    - kubectl config set-cluster local --server="${HH_WP_WEBADMIN_ENDPOINT}"
    - kubectl config set clusters.local.certificate-authority-data "${HH_WP_WEBADMIN_CERTIFICATE_AUTHORITY}"
    - kubectl config set-credentials ${HH_WP_WEBADMIN_USER} --token="${HH_WP_WEBADMIN_USER_TOKEN}"
    - kubectl config set-context "${HH_WP_WEBADMIN_NAMESPACE}" --cluster=local --user=${HH_WP_WEBADMIN_USER} --namespace="${HH_WP_WEBADMIN_NAMESPACE}"
    - kubectl config use-context "${HH_WP_WEBADMIN_NAMESPACE}"
    - kubectl version

    - sed -i "s/latest/$CI_COMMIT_SHA/g" k8-deploy/prod/pdcm-admin-api-deployment.yaml

    - kubectl apply -f k8-deploy/prod/pdcm-admin-api-deployment.yaml --record
    - kubectl rollout status -f k8-deploy/prod/pdcm-admin-api-deployment.yaml

    - kubectl apply -f k8-deploy/prod/pdcm-admin-api-service.yaml --record
    - kubectl get pods,service,deploy,replicaset,ing -n "${HH_WP_WEBADMIN_NAMESPACE}"
  only:
    refs:
      - main
