apiVersion: v1
kind: Service
metadata:
  name: pdcm-admin-api-service
  labels:
    name: pdcm-admin-api-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31304
  selector:
    app: pdcm-admin-api
  type: NodePort
