apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pdcm-admin-api
  namespace: pdx-admin-interface
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pdcm-admin-api
    spec:
      containers:
        - name: pdcm-admin-api
          image: 'pdxfinder/pdcm-admin-api:prod'
          imagePullPolicy: Always
          args:
            - --data-dir=/opt/pdcm-data
            - --data_repo_gitlab_branch=master
            - --data_repo_gitlab_token=DATA_REPO_GITLAB_TOKEN
            - --db_host=DB_PROD_HOST
            - --db_port=DB_PROD_PORT
            - --db_name=DB_PROD_NAME
            - --db_user=DB_PROD_USER
            - --db_password=DB_PROD_PASSWORD
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: debug-port
              containerPort: 5006
              protocol: TCP

          env:
            - name: JAVA_TOOL_OPTIONS
              value: '-Xdebug -agentlib:jdwp=transport=dt_socket,address=0.0.0.0:5006,server=y,suspend=n'
#          envFrom:
#            - configMapRef:
#                name: pdx-admin-api-config

          volumeMounts:
            - name: pv-data
              mountPath: /opt/pdcm-data
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: pdcm-data-pvc

