apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdcm-admin-pvc
  namespace: pdx-admin-interface
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard-nfs-production
