apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pdcm-h2
  namespace: pdx-admin-interface
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pdcm-h2
    spec:
      containers:
        - name: pdcm-h2
          image: 'oscarfonts/h2:1.4.199'
          ports:
          - containerPort: 81
          volumeMounts:
            - name: pv-data
              mountPath: /opt/h2-data
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: pdcm-admin-h2-pvc
