apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdcm-data-dev-pvc
  labels:
    app: pdcm-admin-api-dev
  namespace: pdx-admin-interface-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard-nfs-production
