apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pdcm-admin-api-dev
  namespace: pdx-admin-interface-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pdcm-admin-api-dev
    spec:
      containers:
        - name: pdcm-admin-api-dev
          image: 'pdxfinder/pdcm-admin-api:dev'
          imagePullPolicy: Always
          args:
            - --data-base-location=tcp://hh-rke-wp-webadmin-20-worker-1.caas.ebi.ac.uk:30710
            - --data-dir=/opt/pdcm-data
            - --data_repo_gitlab_branch=dev
            - --data_repo_gitlab_token=DATA_REPO_GITLAB_TOKEN
          ports:
            - containerPort: 8080
#          envFrom:
#            - configMapRef:
#                name: pdx-admin-api-config

          volumeMounts:
            - name: pv-data
              mountPath: /opt/pdcm-data
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: pdcm-data-dev-pvc

