apiVersion: v1
kind: Service
metadata:
  name: pdcm-admin-api-dev-service
  labels:
    name: pdcm-admin-api-dev-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32601
  selector:
    app: pdcm-admin-api-dev
  type: NodePort
